name: lifebox
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # routing
  go_router: ^14.2.7

  # state
  flutter_riverpod: ^2.5.1

  # network
  dio: ^5.7.0

  # utils
  intl: ^0.19.0
  collection: ^1.18.0

  provider: ^6.1.2
  photo_manager: ^3.0.0
  google_mlkit_text_recognition: ^0.13.0
  crypto: ^3.0.3
  photo_manager_image_provider: ^2.0.0

  speech_to_text: ^7.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo-b.png
